version: "3"

dotenv:
  - .env
  - .env.local

env:
  PORT: 8080

vars:
  container_name: tasklify
  container_tag: latest

tasks:

  ## Golang, HTMX, Templ, TailwindCSS, YARN

  dev:
    deps:
      - task: deps
    cmds:
      - npx tailwindcss -i ./input.css -o ./static/css/style.css --watch &
      - air

  build:
    deps:
      - task: deps
      - task: generate
    cmds:
      - docker build -t {{.container_name}}:{{.container_tag}} .

  deps:
    internal: true
    cmds:
      - yarn
      
      - cmd: mkdir -p static/{css,script}
        platforms: [linux, darwin]
      - cmd: cp node_modules/htmx.org/dist/htmx.min.js static/script/.
        platforms: [linux, darwin]
      - cmd: cp node_modules/htmx.org/dist/ext/response-targets.js static/script/.
        platforms: [linux, darwin]

      - cmd: New-Item -ItemType Directory -Force -Path "static\css", "static\script"
        platforms: [windows]
      - cmd: Copy-Item -Path "node_modules\htmx.org\dist\htmx.min.js", "node_modules\htmx.org\dist\ext\response-targets.js" -Destination "static\script\"
        platforms: [windows]

  generate:
    internal: true
    cmds:
      - npx tailwindcss -i ./input.css -o ./static/css/style.css --minify
      - templ generate
      - go generate ./...

  ## Docker compose

  up:
    cmds:
      - docker compose up -d

  down:
    cmds:
      - docker compose down

  purge:
    cmds:
      - docker compose down --volumes